### ISSUE TITLE
Add test case where many devices are slow at responding.

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#137]
This was added as an user reported that piggy only got the power reports every 3-4 minutes.
Check how piggy behaves and add improvements in responsiveness in case piggy is stuck in a slow response cycle.

**Comment by frodeheg** [comment]
A new report from the forum also seems to indicate that the mutex is not released, see here: https://community.homey.app/t/app-pro-piggy-bank/66677/392?u=frodeheg

**Comment by ingepettersen** [comment]
> A new report from the forum also seems to indicate that the mutex is not released, see here: https://community.homey.app/t/app-pro-piggy-bank/66677/392?u=frodeheg

My log below... Note that since I restarted the app in an attempt to fix the issue, it doesn't contain everything since the error began. 

Log ID: 2022-12-25T11:13:50.729Z
App version 0.19.26

+11:13:50.729: Restored state from safe shutdown values 17697.70609555555 2009 Sun Dec 25 2022 11:13:35 GMT+0000 (Coordinated Universal Time) 0
+11:14:6.146: Failed to reduce power usage by 15030W (number of forced on devices: 1)
+11:14:45.936: Failed to reduce power usage by 14625W (number of forced on devices: 1)
+11:15:26.015: Failed to reduce power usage by 14818W (number of forced on devices: 1)
+11:16:5.444: Failed to reduce power usage by 14217W (number of forced on devices: 1)
+11:16:35.873: Failed to reduce power usage by 14305W (number of forced on devices: 1)
+11:17:16.979: Failed to reduce power usage by 14496W (number of forced on devices: 1)
+11:17:45.624: Failed to reduce power usage by 15118W (number of forced on devices: 1)
+11:18:25.838: Failed to reduce power usage by 15001W (number of forced on devices: 1)
+11:19:5.888: Failed to reduce power usage by 15269W (number of forced on devices: 1)
+11:19:45.527: Failed to reduce power usage by 15463W (number of forced on devices: 1)
+11:20:25.895: Failed to reduce power usage by 15510W (number of forced on devices: 1)
+11:21:5.571: Failed to reduce power usage by 15782W (number of forced on devices: 1)
+11:21:35.746: Failed to reduce power usage by 15924W (number of forced on devices: 1)
+11:22:15.510: Failed to reduce power usage by 16187W (number of forced on devices: 1)
+11:22:55.758: Failed to reduce power usage by 16366W (number of forced on devices: 1)
+11:24:15.496: Failed to reduce power usage by 17527W (number of forced on devices: 1)
+11:24:45.299: Failed to reduce power usage by 19999W (number of forced on devices: 1)
+11:25:15.684: Failed to reduce power usage by 19815W (number of forced on devices: 1)
+11:25:55.876: Failed to reduce power usage by 20703W (number of forced on devices: 1)
+11:26:35.615: Failed to reduce power usage by 21103W (number of forced on devices: 1)
+11:27:5.907: Failed to reduce power usage by 21456W (number of forced on devices: 1)
+11:27:45.826: Failed to reduce power usage by 22271W (number of forced on devices: 1)
+11:28:25.780: Failed to reduce power usage by 22249W (number of forced on devices: 1)
+11:28:36.285: Failed to reduce power usage by 22366W (number of forced on devices: 1)
+11:28:55.615: Failed to reduce power usage by 22664W (number of forced on devices: 1)
+11:29:25.961: Failed to reduce power usage by 23800W (number of forced on devices: 1)
+11:29:30.540: Failed checking electricity price API: app_not_found
+11:29:30.544: Please install the app "Strømregning" to fetch electricity prices
+11:29:56.260: Failed to reduce power usage by 23938W (number of forced on devices: 1)
+11:30:35.473: Failed to reduce power usage by 24429W (number of forced on devices: 1)
+11:31:45.671: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:32:15.692: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:32:18.177: Failed checking electricity price API: app_not_found
+11:32:18.184: Please install the app "Strømregning" to fetch electricity prices
+11:32:45.802: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:33:25.655: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:33:56.415: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:34:35.798: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:35:15.971: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:35:46.065: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:36:25.245: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:37:34.273: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:38:5.494: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:38:45.806: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:39:25.558: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:39:55.655: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:40:35.601: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:41:15.725: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:41:55.627: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:42:25.628: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:42:56.231: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:43:35.620: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:44:5.936: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:44:45.825: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:45:56.021: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:46:35.789: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:47:16.375: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:48:25.780: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:49:5.680: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:49:35.616: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:50:6.656: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:50:45.791: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:51:25.485: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:51:55.506: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:52:26.293: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:53:46.151: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:54:25.613: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:55:5.427: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:55:45.735: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:56:26.965: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:57:5.561: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:57:45.706: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:58:26.076: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+11:58:56.054: Failed to reduce power usage by 25097W (number of forced on devices: 1)
+12:1:56.337: Failed checking electricity price API: app_not_found
+12:1:56.345: Please install the app "Strømregning" to fetch electricity prices
+12:2:51.527: Failed checking electricity price API: app_not_found
+12:2:51.534: Please install the app "Strømregning" to fetch electricity prices
+13:1:22.079: Failed checking electricity price API: app_not_found
+13:1:22.085: Please install the app "Strømregning" to fetch electricity prices
+13:47:26.452: Failed checking electricity price API: app_not_found
+13:47:26.457: Please install the app "Strømregning" to fetch electricity prices
+13:51:17.305: Failed checking electricity price API: app_not_found
+13:51:17.311: Please install the app "Strømregning" to fetch electricity prices

**Comment by ingepettersen** [comment]
I also checked my Tibber Pulse data. Seems it took a nap around when this problem started... That's a quite unusual occurrence, and is probably related. 
![Screenshot_20221225-151607](https://user-images.githubusercontent.com/47382243/209471544-5fdb7e0e-00d3-44a0-82fd-a54e30a10f3c.png)

**Comment by frodeheg** [comment]
Thank you, that is definitively related. I will try to improve how Piggy reacts to this situation...

**Comment by frodeheg** [comment]
The test case above was tested against version 0.19.26 and indeed did add up several hours of power until power was reported again.

The current unpublished test version did not have these issues, however it had the problem that the hours with missing data was reported as ok.

**Comment by frodeheg** [comment]
Closing ticket.
When the issue occurs now the hour with missing data will be marked as inaccurate and the calculated power will be capped so it no longer last longer than from the start of the hour. The effect of this is that no power will be accumulated for the end of the hours with missing power data. It could have been estimated though, but since it's an error situation even the estimates will be off, so it's skipped for now. (Might be improved in the future though)

Still need to run this for local testing some more before pushing it to community testing though.
