### ISSUE TITLE
Make end time in car charging accept variables

### ISSUE THREAD

**Issue by dooniem** [frodeheg/no.sparegris#22]
If someone is reading this and agree, it’s helpful if you comment with “+1” or similar to prove the usefulness 😅

My arguments for this enhancement:

- Editing time in an advanced flow on mobile device will be possible 
- Exceptions to routines happen, end time will vary. Changing should be quick and easy

There are numerous ways of enabling this. 
The simplest would be a text field similar to how “wanted power” is inserted in the flow card. A description saying the ‘time needs to be inserted as “hh:mm” (without the quotes)’ and maybe show a error message on PBs main page where all the other errors are shown if PB fails to extract time.

In Homey’s card for “between time”, they inform if end time is smaller than start time, next day will be assumed. I reckon your code does the same. But the help text is reassuring 

My enhancement was written purely for editing end time **before** triggering the flow card. I don’t ask for catching a changed variable while charging and make a new calculation. Though that would be a plus 😅 Let that be a future enhancement

**Comment by frodeheg** [comment]
Ok, so I have checked a little bit and found out that both of the following options are completely backward-compatible so will not destroy any older flows which is very good news:
* Changing the existing end time input in the existing actions from time to text
* Changing the existing end time input in the existing actions from time to number

The former allows you to specify any time, but could also result in problems when writing illegal times, so a guard must be added. Also, with this I need to make the flows stop at the correct minute which it doesn't do right now.
The latter will only specify the hour, which makes it perfect because the current code only stops when entering new hours anyway so minimal updates, and the number input can have a min/max guard so only legal numbers can be entered.

What are your preferences?

**Comment by dooniem** [comment]
I think the latter will be less intuitive. Driving for work at 6:30 will have you write 7.
And if you ever upgrade from number to text, people will potentially have to redo their variable and wake up to a non-charge night.
I think the best option from a user’s intuition would be text, but I can see that means more coding than the latter…
