### ISSUE TITLE
"Override device" flow card lists out-of-date device/zone names

### ISSUE THREAD

**Issue by ugumba** [frodeheg/no.sparegris#56]
I renamed most of my devices and zones (standardized on English).
When updating the existing "override device" flow cards, they listed the old names.
After restarting PB, all was OK again.

**Comment by frodeheg** [comment]
I am not sure if I can do anything about this. When the flow cards request a state request from the app then the app will immediately fetch the up-to-date state from Homey and return this to the flow card. As far as I know, there is no way to send an updated state to the flow card without the flow card requesting it.

If you're also getting the old zones listed when creating new zone cards or trying to change the zone on an existing card, then the state returned from the homey API has to be cached because this is not cached by the app. If so, I am unsure if I can do anything about this either.

**Comment by ugumba** [comment]
Makes sense. It's good enough to document that a PB restart is needed.

**Comment by frodeheg** [comment]
I am not sure if you're happy with the change in the hint text of the zone flows as posted above, but it was the only thing I could think of as an improvement. Please shout out if this was not enough.
