### ISSUE TITLE
Add an option to start a charging cycle by default when a car is connected.

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#89]
See comment: https://community.homey.app/t/app-pro-piggy-bank/66677/295?u=frodeheg
* If charger is On, then start charging immediately
* If charger is Off, then start charging won’t start
* If charger is Auto, then start charging during low-cost hours (or as defined in the variable under charger and price settings)

**Comment by frodeheg** [comment]
Some constraints have to be made when to select end time, otherwise it's difficult to find the cheapest hours in the interval.

**Comment by ThomasEdvardsen** [comment]
I am a little unsure of what is intended with this functionality. Maybe it matches my need.

I could imagine making a simplified management of the charging, where you don't need to set up a charging cycle to charge. All I really need is for the piggy bank to regulate the charging current so that I do not exceed 10kW per hour.

I therefore do not want it to set the charging current to 0A, but just leave it at max all the time when not charging. Piggy bank can then regulate the charging current down if necessary to keep the 10kW limit.

It also means that I can preheat the car before I go out for a drive, without the piggy bank throttling the power to the charger. My car basically wants to have access to electricity all the time, e.g. to be able to temper the battery if necessary.

In practice, I have other apps (Android) to calculate when the car should charge, based on the fact that they know the car's battery percentage.
