### ISSUE TITLE
Dynamically calculate how much energy is charged per hour and use it in estimates

### ISSUE THREAD

**Issue by frodeheg** [frodeheg/no.sparegris#98]
Currently the estimates are a bit off. If dynamically calculating how much is being charged per hour then the estimates for when to charge will become more accurate.

**Comment by dooniem** [comment]
I agree with "very dependant". It will never be right, but static 75% is too often completely wrong. So a manual would be welcome. Having said that I still think having to manually adjust during spring to summer, and then again from summer to winter seems unnecessary. That's why I think having both options, manual (which could be a quick and "cheap" step 1) and then auto mode which finds the mean between last 2 sessions, and hence will gradually adjust for outside temp and general consumption.

Hmm. Maybe even let the user change number of sessions to find the mean from, to adjust for their own random day/night charging sessions?
